---
- name: Show distribution and IP
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather facts (Ubuntu/Debian only)
      setup:
      when: inventory_hostname in ["host1", "host2"]

    - name: Print distro and IP (Ubuntu/Debian)
      debug:
        msg: '{{ inventory_hostname }}: {{ ansible_distribution }} {{ ansible_default_ipv4.address }}'
      when: inventory_hostname in ["host1", "host2"]

    - name: Print distro (CentOS 7)
      raw: cat /etc/os-release | grep PRETTY_NAME
      register: os_release
      when: inventory_hostname == "host3"

    - name: Show CentOS distro
      debug:
        msg: '{{ inventory_hostname }}: {{ os_release.stdout }}'
      when: inventory_hostname == "host3"

    - name: Print IP (CentOS 7)
      raw: hostname -I | awk '{print $1}'
      register: centos_ip
      when: inventory_hostname == "host3"

    - name: Show CentOS IP
      debug:
        msg: '{{ inventory_hostname }}: {{ centos_ip.stdout }}'
      when: inventory_hostname == "host3"
