---
- name: Ensure user student9 exists on all hosts
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Create student9 on Ubuntu/Debian
      user:
        name: student9
        state: present
        create_home: yes
        shell: /bin/bash
      when: inventory_hostname in ["host1", "host2"]

    - name: Create student9 on CentOS 7
      raw: sudo useradd -m -s /bin/bash student9 || echo "user student9 already exists"
      when: inventory_hostname == "host3"
